### ISSUE TITLE
请问是否有官方网址？

### ISSUE THREAD

**Issue by liyaooi** [bugaosuni59/TH-CPL#3]
请问这份《清华大学计算机学科推荐学术会议和期刊列表 》是否有发布的官方网址？我在清华大学官网找了很久没找到。多谢

**Comment by liyaooi** [comment]
已找到，谢谢。[https://numbda.cs.tsinghua.edu.cn/~yuwj/TH-CPL.pdf](https://numbda.cs.tsinghua.edu.cn/~yuwj/TH-CPL.pdf)

**Comment by xianlong59** [comment]
感谢提供链接，好久没看这个 repo 了，之前是 19 年这个列表刚出的时候随手整理的，现在看来其实没啥意义了，我贴个官方 pdf 链接上去导个流




不告诉你！
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "reply+AGB4XS4ZF3NDLMFNSBNB2IGDGSN3BEVBNHHEMHNRQE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月12日(星期四) 中午11:34
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [bugaosuni59/TH-CPL] 请问是否有官方网址？ (Issue #3)




已找到，谢谢。https://numbda.cs.tsinghua.edu.cn/~yuwj/TH-CPL.pdf

—
Reply to this email directly, view it on GitHub or unsubscribe.
You are receiving this email because you are subscribed to this thread.

Triage notifications on the go with GitHub Mobile for iOS or Android.
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
